name: maisdata
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  url_launcher: ^5.4.7
  mask_text_input_formatter: ^1.0.6
  intl: ^0.16.1
  enum_to_string: ^1.0.13

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: SF UI Display
      fonts:
        - asset: fonts/sf/sf-ui-display.otf

  uses-material-design: true

  